# Generated by Django 5.0.3 on 2024-03-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[("""         
            CREATE TABLE IF NOT EXISTS "profiles" (
            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" integer NOT NULL,
            "name" varchar(100),
            "about" text,
            "created_at" timestamp,
            "updated_at" timestamp
            );
            """), 
            (""" 
            ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");          
            """)],
            reverse_sql=[("""
                ALTER TABLE profiles DROP CONSTRAINT profiles_user_id_fkey
            """), ("""
                DROP TABLE IF EXISTS profiles;
            """)]
        )
]
