# Generated by Django 5.0.3 on 2024-03-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_profiles'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("""
                CREATE TABLE "questions" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "user_id" integer NOT NULL,
                "title" varchar(100),
                "content" text,
                "created_at" timestamp,
                "updated_at" timestamp
                );
            """), 
            ("""
                ALTER TABLE "questions" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
            """)],
            reverse_sql=[("""
                ALTER TABLE profiles DROP CONSTRAINT questions_user_id_fkey
            """), ("""
                DROP TABLE IF EXISTS questions;
            """)]
        )
    ]
