# Generated by Django 5.0.3 on 2024-03-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_answers'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(""" 
            CREATE TABLE "replies" (
            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" integer NOT NULL,
            "answer_id" integer NOT NULL,
            "created_at" timestamp,
            "updated_at" timestamp
            );
            """), 
            ("""
                ALTER TABLE "replies" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
            """),
            ("""
                ALTER TABLE "replies" ADD FOREIGN KEY ("answer_id") REFERENCES "answers" ("id");
            """)],
            reverse_sql=[
                (""" 
                    ALTER TABLE profiles DROP CONSTRAINT replies_user_id_fkey
                """),
                (""" 
                    ALTER TABLE profiles DROP CONSTRAINT replies_answer_id_fkey
                """),
                ("""
                    DROP TABLE IF EXISTS replies;
                """)
            ]
        )
    ]
