# Generated by Django 5.0.3 on 2024-03-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_replies'),
    ]

    operations = [
    ]
