# Generated by Django 5.0.3 on 2024-03-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_replies'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("""
                CREATE TABLE "vote_questions" (
                "user_id" integer NOT NULL,
                "question_id" integer NOT NULL,
                "vote" integer NOT NULL,
                "created_at" timestamp,
                "updated_at" timestamp,
                PRIMARY KEY ("user_id", "question_id")
                );
            """), 
            (""" 
                ALTER TABLE "vote_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");       
            """), 
            ("""
                ALTER TABLE "vote_questions" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
            """)],
            reverse_sql=[("""
                ALTER TABLE vote_questions DROP CONSTRAINT vote_questions_question_id_fkey
            """), 
            ("""
                ALTER TABLE vote_questions DROP CONSTRAINT vote_questions_user_id_fkey
            """), 
            ("""
                DROP TABLE IF EXISTS vote_questions;
            """)]
        )
    ]
