# Generated by Django 5.0.3 on 2024-03-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_vote_answers'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("""
                CREATE TABLE IF NOT EXISTS "categories" (
                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "name" varchar(100) UNIQUE NOT NULL,
                    "created_at" timestamp,
                    "updated_at" timestamp
                );
            """),],
            reverse_sql=[("""
                DROP TABLE IF EXISTS categories;
            """)]
        )
    ]
