# Generated by Django 5.0.3 on 2024-03-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_tags'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("""
                CREATE TABLE IF NOT EXISTS "saved" (
                    "user_id" integer NOT NULL,
                    "question_id" integer NOT NULL,
                    "created_at" timestamp,
                    "updated_at" timestamp,
                    PRIMARY KEY ("user_id", "question_id")
                );
            """), 
            (""" 
                ALTER TABLE "saved" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
            """),
            (""" 
                ALTER TABLE "saved" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");        
            """)],
            reverse_sql=[("""
                ALTER TABLE saved DROP CONSTRAINT saved_user_id_fkey
            """), ("""
                ALTER TABLE saved DROP CONSTRAINT saved_question_id_fkey
            """), ("""
                DROP TABLE IF EXISTS saved;
            """)]
        )
    ]
