# Generated by Django 5.0.3 on 2024-03-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_saved'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("""
                    ALTER TABLE "replies" ADD content text;
                """)],
            reverse_sql=[
                (""" 
                    ALTER TABLE "replies" DROP COLUMN content;
                """),
            ]
        )
    ]
